### ISSUE TITLE
Problem to setup PyAppBuilder

### ISSUE THREAD

**Issue by rolffank** [Embarcadero/PythonFMXBuilder#13]
Hi

If I run PythonFMXBuilder I have no devices in the combobox top right. If I click on the update or refresh button (arrow circle) I get following messages: 

Check out for more command details:
http://delphi.org/2013/11/installing-and-running-android-apps-from-command-line/

ExecCmd: C:\Users\Public\Documents\Embarcadero\Studio\22.0\CatalogRepository\AndroidSDK-2525-22.0.44500.8973\platform-tools\adb.exe devices
List of devices attached

If I click the gear icon I get following error: The specified path was not found
[C:\Program Files\PythonFMXBuilder\apps\PyAppTest\assets\internal\build.zip].

I installed PythonFMXBuilder in C:\Program Files\PythonFMXBuilder\
Maybe problems to save data/create folders because of user rights?

**Comment by rolffank** [comment]
Hi
I moved PythonFMXBuilder from program to a data folder. Now I could build the app but still no devices to choose. Any idea what could be wrong? I updated my RAD Studio version from 11 to 11.1 (uninstalled 11 and installed 11.1) but during installation I got an error 'List index out of bounds (-1)' during installation of Android Common Files Professional features. 
Is this a known installation bug?

**Comment by rolffank** [comment]
Problem solved!!
I connected my mobile and was able to deploy the app! In an older RAD Studio version I used an Android emulator and could select multiple devices. I thought it works the same way here.

I would like to migrate a small python console application to Android.  In PythonFMXBuilder I can choose python v 3.8, 3.9 or 3.10. Did PythonFMXBuilder find these versions on my pc or are these different isolated versions installed by PythonFMXBuilder? How can I install additional packages?

Thanks for this nice tool!! Great job!

**Comment by Priyatham10** [comment]
Hi @rolffank . Great you figured out the solution to work. The whole step by step guide is in wiki for your reference: https://github.com/Embarcadero/PythonFMXBuilder/wiki/Step-by-step-guide-to-create-an-Android-application-using-PythonFMXBuilder. Also, added the samples on how to use here: https://github.com/Embarcadero/PythonFMXBuilder/tree/main/Samples.

Please post any doubts are issues you face further.

**Comment by rolffank** [comment]
Hi Priyatham
Thanks for your prompt answer and your helpful links!
I was surprised at the size of the app on my mobile: 413 MB !! (app 117 MB, user data 296 MB). Fortunately, the app can be moved to the SD card! Is there potential to reduce the size? Is the python library in the user data or what blows up the size so much?

**Comment by lmbelo** [comment]
Hi @rolffank,

we are currently working on a new version that will reduce the final app size. However, it wouldn't get much smaller, since we create a whole Python environment within the app itself.

**Comment by rolffank** [comment]
Hi Lucas
Thanks for the quick reply! Good luck reducing the size! 
Kind regards, Rolf
