### ISSUE TITLE
File open dialog for Main.py and other files

### ISSUE THREAD

**Issue by jimmckeeth** [Embarcadero/PythonFMXBuilder#2]
Right now the main.py script is just pasted into the memo. Instead we need an option for the user to browse for the main.py, and any other files they want to include in the project.

**Comment by Priyatham10** [comment]
Added this capability. @jimmckeeth Please think of info that we can keep in the "About" tab. My idea is to:
- Tell what our app is about
- Provide License details
- App version
etc..
