### ISSUE TITLE
Create documentation around common ADB commands

### ISSUE THREAD

**Issue by jimmckeeth** [Embarcadero/PythonFMXBuilder#4]
Create documentation within the project around common ADB commands based on my blog post
http://delphi.org/2013/11/installing-and-running-android-apps-from-command-line/

**Comment by Priyatham10** [comment]
Working on this now..  Will be soon available soon on the wiki page.

**Comment by Priyatham10** [comment]
Documentation is created for Android SDK set-up here: https://github.com/Embarcadero/PythonFMXBuilder/wiki/Android-SDK-guide. PythonFMXBuilder takes care of necessary ADB commands for automatic uninstalling and installing the Android app through ADB.
