### ISSUE TITLE
Getting Started Guide

### ISSUE THREAD

**Issue by jimmckeeth** [Embarcadero/PythonFMXBuilder#5]
Guide showing steps to get started that don't assume Delphi is installed

1. Installing Android SDK if necessary
2. Installing Adopt Open JDK if necessary
3. Installing PythonFMXBuilder
4. Deploying an application
5. Troubleshooting

**Comment by Priyatham10** [comment]
Added the guide to wiki at the following link: https://github.com/Embarcadero/PythonFMXBuilder/wiki/Step-by-step-guide-to-create-an-Android-application-using-PythonFMXBuilder
